server:
  port: 7890

spring:
  application-name: charyeot

external:
  riot:
    url: "https://%s.api.riotgames.com"
    api-key: "RGAPI-94dd5cc2-a72f-4fdd-a73d-b4f12b42fcc8"
  nimble:
    url: "https://open-api.bser.io"
    api-key: "I6to7of3wP2fjnROgCqsv3A0zVURII2T9GwqJhRj"

gemini:
  api-key: AIzaSyCIf9ltjJrPaIc_1RkH34CoMzAnH-B-Rhg
